### ISSUE TITLE
AxisError('axis 2 is out of bounds for array of dimension 2')

### ISSUE THREAD

**Issue by Nal44** [kapoorlab/VollSeg#6]
Hi,

I am trying to use Vollseg in Napari, but I always get this recurrent error (see below):

The image is 1 channel (DAPI) and 2D (YX) .TIF

Stardist is running fine, but would like to try Vollseg...

Could you help please ?

Thanks for Vollseg and sharing !
antho

---------------------------------------------------------------------------
AxisError                                 Traceback (most recent call last)
File ~\AppData\Local\napari-0.4.16.dev104a\envs\napari-0.4.16.dev104\lib\site-packages\superqt\utils\_qthreading.py:616, in create_worker.<locals>.reraise(e=AxisError('axis 2 is out of bounds for array of dimension 2'))
    615 def reraise(e):
--> 616     raise e
        e = AxisError('axis 2 is out of bounds for array of dimension 2')

File ~\AppData\Local\napari-0.4.16.dev104a\envs\napari-0.4.16.dev104\lib\site-packages\superqt\utils\_qthreading.py:176, in WorkerBase.run(self=<napari._qt.qthreading.FunctionWorker object>)
    174     warnings.filterwarnings("always")
    175     warnings.showwarning = lambda *w: self.warned.emit(w)
--> 176     result = self.work()
        self = <napari._qt.qthreading.FunctionWorker object at 0x000002054C7B9EE0>
    177 if isinstance(result, Exception):
    178     if isinstance(result, RuntimeError):
    179         # The Worker object has likely been deleted.
    180         # A deleted wrapped C/C++ object may result in a runtime
    181         # error that will cause segfault if we try to do much other
    182         # than simply notify the user.

File ~\AppData\Local\napari-0.4.16.dev104a\envs\napari-0.4.16.dev104\lib\site-packages\superqt\utils\_qthreading.py:356, in FunctionWorker.work(self=<napari._qt.qthreading.FunctionWorker object>)
    355 def work(self) -> _R:
--> 356     return self._func(*self._args, **self._kwargs)
        self._func = <function plugin_wrapper_vollseg.<locals>._Segment at 0x000002053D6CD3A0>
        self = <napari._qt.qthreading.FunctionWorker object at 0x000002054C7B9EE0>
        self._args = (StarDist2D(versatile2dcellsallanthoMULIPLEGPUnolargenuclei): YXC → YXC
├─ Directory: \\bir-titan\Anthony\software\stardist-master\examples\2D\models\versatile2dcellsallanthoMULIPLEGPUnolargenuclei
└─ Config2D(axes='YXC', backbone='unet', grid=(2, 2), n_channel_in=1, n_channel_out=33, n_classes=None, n_dim=2, n_rays=32, net_conv_after_unet=128, net_input_shape=[None, None, 1], net_mask_shape=[None, None, 1], train_background_reg=0.0001, train_batch_size=8, train_checkpoint='weights_best.h5', train_checkpoint_epoch='weights_now.h5', train_checkpoint_last='weights_last.h5', train_class_weights=[1, 1], train_completion_crop=32, train_dist_loss='mae', train_epochs=400, train_foreground_only=0.9, train_learning_rate=0.0003, train_loss_weights=[1, 0.2], train_n_val_patches=None, train_patch_size=[256, 256], train_reduce_lr={'factor': 0.5, 'patience': 40, 'min_delta': 0}, train_sample_cache=True, train_shape_completion=False, train_steps_per_epoch=100, train_tensorboard=True, unet_activation='relu', unet_batch_norm=False, unet_dropout=0.0, unet_kernel_size=[3, 3], unet_last_activation='relu', unet_n_conv_per_depth=2, unet_n_depth=3, unet_n_filter_base=32, unet_pool=[2, 2], unet_prefix='', use_gpu=False), UNET(Xenopus Tissue (2D)): YXC → YXC
├─ Directory: None
└─ Config(axes='YXC', n_channel_in=1, n_channel_out=1, n_dim=2, probabilistic=False, train_batch_size=1, train_checkpoint='weights_best.h5', train_checkpoint_epoch='weights_now.h5', train_checkpoint_last='weights_last.h5', train_epochs=200, train_learning_rate=1e-06, train_loss='mae', train_reduce_lr={'patience': 5, 'factor': 0.5}, train_steps_per_epoch=400, train_tensorboard=True, unet_input_shape=[None, None, 1], unet_kern_size=3, unet_last_activation='linear', unet_n_depth=5, unet_n_first=64, unet_residual=True), None, <class 'numpy.ndarray'> (1040, 1392) uint16, 'YX', None, [1.0, 1.0])
        self._kwargs = {}

File ~\AppData\Roaming\Python\Python38\site-packages\vollseg_napari\_dock_widget.py:2121, in plugin_wrapper_vollseg.<locals>._Segment(model_star=StarDist2D(versatile2dcellsallanthoMULIPLEGPUnol... unet_pool=[2, 2], unet_prefix='', use_gpu=False), model_unet=UNET(Xenopus Tissue (2D)): YXC → YXC
├─ Director...t_n_depth=5, unet_n_first=64, unet_residual=True), model_roi=None, x=<class 'numpy.ndarray'> (1040, 1392) uint16, axes='YX', noise_model=None, scale_out=[1.0, 1.0])
   2117 @thread_worker (connect = {"returned": return_segment } )        
   2118 def _Segment(model_star, model_unet,  model_roi, x, axes, noise_model, scale_out):
-> 2121     res = VollSeg(
        x = <class 'numpy.ndarray'> (1040, 1392) uint16
        model_unet = UNET(Xenopus Tissue (2D)): YXC → YXC
├─ Directory: None
└─ Config(axes='YXC', n_channel_in=1, n_channel_out=1, n_dim=2, probabilistic=False, train_batch_size=1, train_checkpoint='weights_best.h5', train_checkpoint_epoch='weights_now.h5', train_checkpoint_last='weights_last.h5', train_epochs=200, train_learning_rate=1e-06, train_loss='mae', train_reduce_lr={'patience': 5, 'factor': 0.5}, train_steps_per_epoch=400, train_tensorboard=True, unet_input_shape=[None, None, 1], unet_kern_size=3, unet_last_activation='linear', unet_n_depth=5, unet_n_first=64, unet_residual=True)
        model_star = StarDist2D(versatile2dcellsallanthoMULIPLEGPUnolargenuclei): YXC → YXC
├─ Directory: \\bir-titan\Anthony\software\stardist-master\examples\2D\models\versatile2dcellsallanthoMULIPLEGPUnolargenuclei
└─ Config2D(axes='YXC', backbone='unet', grid=(2, 2), n_channel_in=1, n_channel_out=33, n_classes=None, n_dim=2, n_rays=32, net_conv_after_unet=128, net_input_shape=[None, None, 1], net_mask_shape=[None, None, 1], train_background_reg=0.0001, train_batch_size=8, train_checkpoint='weights_best.h5', train_checkpoint_epoch='weights_now.h5', train_checkpoint_last='weights_last.h5', train_class_weights=[1, 1], train_completion_crop=32, train_dist_loss='mae', train_epochs=400, train_foreground_only=0.9, train_learning_rate=0.0003, train_loss_weights=[1, 0.2], train_n_val_patches=None, train_patch_size=[256, 256], train_reduce_lr={'factor': 0.5, 'patience': 40, 'min_delta': 0}, train_sample_cache=True, train_shape_completion=False, train_steps_per_epoch=100, train_tensorboard=True, unet_activation='relu', unet_batch_norm=False, unet_dropout=0.0, unet_kernel_size=[3, 3], unet_last_activation='relu', unet_n_conv_per_depth=2, unet_n_depth=3, unet_n_filter_base=32, unet_pool=[2, 2], unet_prefix='', use_gpu=False)
        axes = 'YX'
        noise_model = None
        model_roi = None
        plugin_star_parameters = <FunctionGui plugin_star_parameters(norm_image=True, perc_low=1.0, perc_high=99.8, prob_thresh=0.5, nms_thresh=0.4, set_thresholds=False, n_tiles=(1, 1), star_model_axes='YXC[1]', defaults_star_parameters_button=False)>
        plugin_extra_parameters = <FunctionGui plugin_extra_parameters(min_size_mask=1.0, min_size=1.0, max_size=10000000.0, prob_map_watershed=True, dounet=True, isRGB=False, seedpool=True, slicemerge=False, iouthresh=0.5, unet_model_axes='YXC[1]', den_model_axes='', defaults_vollseg_parameters_button=False)>
   2122         x,
   2123         model_unet,
   2124         model_star,
   2125         axes=axes,
   2126         noise_model=noise_model,
   2127         roi_model =  model_roi,
   2128       
   2129         prob_thresh=plugin_star_parameters.prob_thresh.value,
   2130         nms_thresh=plugin_star_parameters.nms_thresh.value,
   2131         min_size_mask=plugin_extra_parameters.min_size_mask.value,
   2132         min_size=plugin_extra_parameters.min_size.value,
   2133         seedpool= plugin_extra_parameters.seedpool.value,
   2134         max_size=plugin_extra_parameters.max_size.value,
   2135         n_tiles=plugin_star_parameters.n_tiles.value,
   2136         UseProbability=plugin_extra_parameters.prob_map_watershed.value,
   2137         dounet=plugin_extra_parameters.dounet.value,
   2138         donormalize=plugin_star_parameters.norm_image.value,
   2139         lower_perc=plugin_star_parameters.perc_low.value, 
   2140         upper_perc=plugin_star_parameters.perc_high.value,
   2141         RGB = plugin_extra_parameters.isRGB.value,           
   2142         slice_merge = plugin_extra_parameters.slicemerge.value,
   2143         iou_threshold = plugin_extra_parameters.iouthresh.value
   2144         )   
   2146     pred = res, scale_out   
   2147     return pred  

File ~\AppData\Roaming\Python\Python38\site-packages\vollseg\helpers.py:1060, in VollSeg(image=<class 'numpy.ndarray'> (1040, 1392) uint16, unet_model=UNET(Xenopus Tissue (2D)): YXC → YXC
├─ Director...t_n_depth=5, unet_n_first=64, unet_residual=True), star_model=StarDist2D(versatile2dcellsallanthoMULIPLEGPUnol... unet_pool=[2, 2], unet_prefix='', use_gpu=False), roi_model=None, axes='YX', noise_model=None, prob_thresh=0.5, nms_thresh=0.4, min_size_mask=1.0, min_size=1.0, max_size=10000000.0, n_tiles=(1, 1), UseProbability=True, globalthreshold=0.2, extent=0, donormalize=True, lower_perc=1.0, upper_perc=99.8, dounet=True, seedpool=True, save_dir=None, Name='Result', startZ=0, slice_merge=False, iou_threshold=0.5, RGB=False)
   1057 # If stardist model is supplied we use this method
   1058 if star_model is not None:
-> 1060     res = VollSeg2D(image, unet_model, star_model, roi_model=roi_model,  noise_model=noise_model, prob_thresh=prob_thresh, nms_thresh=nms_thresh,  donormalize=donormalize, lower_perc=lower_perc, upper_perc=upper_perc, axes=axes, min_size_mask=min_size_mask, min_size=min_size,
        star_model = StarDist2D(versatile2dcellsallanthoMULIPLEGPUnolargenuclei): YXC → YXC
├─ Directory: \\bir-titan\Anthony\software\stardist-master\examples\2D\models\versatile2dcellsallanthoMULIPLEGPUnolargenuclei
└─ Config2D(axes='YXC', backbone='unet', grid=(2, 2), n_channel_in=1, n_channel_out=33, n_classes=None, n_dim=2, n_rays=32, net_conv_after_unet=128, net_input_shape=[None, None, 1], net_mask_shape=[None, None, 1], train_background_reg=0.0001, train_batch_size=8, train_checkpoint='weights_best.h5', train_checkpoint_epoch='weights_now.h5', train_checkpoint_last='weights_last.h5', train_class_weights=[1, 1], train_completion_crop=32, train_dist_loss='mae', train_epochs=400, train_foreground_only=0.9, train_learning_rate=0.0003, train_loss_weights=[1, 0.2], train_n_val_patches=None, train_patch_size=[256, 256], train_reduce_lr={'factor': 0.5, 'patience': 40, 'min_delta': 0}, train_sample_cache=True, train_shape_completion=False, train_steps_per_epoch=100, train_tensorboard=True, unet_activation='relu', unet_batch_norm=False, unet_dropout=0.0, unet_kernel_size=[3, 3], unet_last_activation='relu', unet_n_conv_per_depth=2, unet_n_depth=3, unet_n_filter_base=32, unet_pool=[2, 2], unet_prefix='', use_gpu=False)
        axes = 'YX'
        noise_model = None
        roi_model = None
        unet_model = UNET(Xenopus Tissue (2D)): YXC → YXC
├─ Directory: None
└─ Config(axes='YXC', n_channel_in=1, n_channel_out=1, n_dim=2, probabilistic=False, train_batch_size=1, train_checkpoint='weights_best.h5', train_checkpoint_epoch='weights_now.h5', train_checkpoint_last='weights_last.h5', train_epochs=200, train_learning_rate=1e-06, train_loss='mae', train_reduce_lr={'patience': 5, 'factor': 0.5}, train_steps_per_epoch=400, train_tensorboard=True, unet_input_shape=[None, None, 1], unet_kern_size=3, unet_last_activation='linear', unet_n_depth=5, unet_n_first=64, unet_residual=True)
        image = <class 'numpy.ndarray'> (1040, 1392) uint16
        prob_thresh = 0.5
        nms_thresh = 0.4
        donormalize = True
        lower_perc = 1.0
        upper_perc = 99.8
        min_size_mask = 1.0
        min_size = 1.0
        RGB = False
        n_tiles = (1, 1)
        max_size = 10000000.0
        dounet = True
        UseProbability = True
   1061                     max_size=max_size, dounet=dounet, n_tiles=n_tiles, UseProbability=UseProbability, RGB=RGB)
   1063 # If there is no stardist model we use unet model or denoising model or both to get the semantic segmentation
   1064 if star_model is None:

File ~\AppData\Roaming\Python\Python38\site-packages\vollseg\helpers.py:866, in VollSeg2D(image=<class 'numpy.ndarray'> (1040, 1392) uint16, unet_model=UNET(Xenopus Tissue (2D)): YXC → YXC
├─ Director...t_n_depth=5, unet_n_first=64, unet_residual=True), star_model=StarDist2D(versatile2dcellsallanthoMULIPLEGPUnol... unet_pool=[2, 2], unet_prefix='', use_gpu=False), noise_model=None, roi_model=None, prob_thresh=0.5, nms_thresh=0.4, axes='YX', min_size_mask=1.0, min_size=1.0, max_size=10000000.0, dounet=True, n_tiles=(1, 1), donormalize=True, lower_perc=1.0, upper_perc=99.8, UseProbability=True, RGB=False, seedpool=True)
    864 print('Stardist segmentation on Image')
    865 if donormalize:
--> 866     patch_star = normalize(patch, lower_perc, upper_perc, axis=(0, 1, 2)) 
        patch = <class 'numpy.ndarray'> (1040, 1392) uint16
        lower_perc = 1.0
        upper_perc = 99.8
    867 else:
    868     patch_star = patch

File ~\AppData\Roaming\Python\Python38\site-packages\csbdeep\utils\utils.py:54, in normalize(x=<class 'numpy.ndarray'> (1040, 1392) uint16, pmin=1.0, pmax=99.8, axis=(0, 1, 2), clip=False, eps=1e-20, dtype=<class 'numpy.float32'>)
     51 def normalize(x, pmin=3, pmax=99.8, axis=None, clip=False, eps=1e-20, dtype=np.float32):
     52     """Percentile-based image normalization."""
---> 54     mi = np.percentile(x,pmin,axis=axis,keepdims=True)
        np = <module 'numpy' from 'C:\\Users\\m197816\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\__init__.py'>
        x = <class 'numpy.ndarray'> (1040, 1392) uint16
        pmin = 1.0
        axis = (0, 1, 2)
     55     ma = np.percentile(x,pmax,axis=axis,keepdims=True)
     56     return normalize_mi_ma(x, mi, ma, clip=clip, eps=eps, dtype=dtype)

File <__array_function__ internals>:5, in percentile(*args=(<class 'numpy.ndarray'> (1040, 1392) uint16, 1.0), **kwargs={'axis': (0, 1, 2), 'keepdims': True})

File ~\AppData\Roaming\Python\Python38\site-packages\numpy\lib\function_base.py:3867, in percentile(a=<class 'numpy.ndarray'> (1040, 1392) uint16, q=<class 'numpy.ndarray'> () float64, axis=(0, 1, 2), out=None, overwrite_input=False, interpolation='linear', keepdims=True)
   3865 if not _quantile_is_valid(q):
   3866     raise ValueError("Percentiles must be in the range [0, 100]")
-> 3867 return _quantile_unchecked(
        q = <class 'numpy.ndarray'> () float64
        a = <class 'numpy.ndarray'> (1040, 1392) uint16
        axis = (0, 1, 2)
        out = None
        overwrite_input = False
        interpolation = 'linear'
        keepdims = True
   3868     a, q, axis, out, overwrite_input, interpolation, keepdims)

File ~\AppData\Roaming\Python\Python38\site-packages\numpy\lib\function_base.py:3986, in _quantile_unchecked(a=<class 'numpy.ndarray'> (1040, 1392) uint16, q=<class 'numpy.ndarray'> () float64, axis=(0, 1, 2), out=None, overwrite_input=False, interpolation='linear', keepdims=True)
   3983 def _quantile_unchecked(a, q, axis=None, out=None, overwrite_input=False,
   3984                         interpolation='linear', keepdims=False):
   3985     """Assumes that q is in [0, 1], and is an ndarray"""
-> 3986     r, k = _ureduce(a, func=_quantile_ureduce_func, q=q, axis=axis, out=out,
        a = <class 'numpy.ndarray'> (1040, 1392) uint16
        q = <class 'numpy.ndarray'> () float64
        axis = (0, 1, 2)
        out = None
        overwrite_input = False
        interpolation = 'linear'
   3987                     overwrite_input=overwrite_input,
   3988                     interpolation=interpolation)
   3989     if keepdims:
   3990         return r.reshape(q.shape + k)

File ~\AppData\Roaming\Python\Python38\site-packages\numpy\lib\function_base.py:3544, in _ureduce(a=<class 'numpy.ndarray'> (1040, 1392) uint16, func=<function _quantile_ureduce_func>, **kwargs={'axis': (0, 1, 2), 'interpolation': 'linear', 'out': None, 'overwrite_input': False, 'q': <class 'numpy.ndarray'> () float64})
   3542 keepdim = list(a.shape)
   3543 nd = a.ndim
-> 3544 axis = _nx.normalize_axis_tuple(axis, nd)
        axis = (0, 1, 2)
        nd = 2
        _nx = <module 'numpy.core.numeric' from 'C:\\Users\\m197816\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\core\\numeric.py'>
   3546 for ax in axis:
   3547     keepdim[ax] = 1

File ~\AppData\Roaming\Python\Python38\site-packages\numpy\core\numeric.py:1385, in normalize_axis_tuple(axis=(0, 1, 2), ndim=2, argname=None, allow_duplicate=False)
   1383         pass
   1384 # Going via an iterator directly is slower than via list comprehension.
-> 1385 axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
        axis = (0, 1, 2)
        argname = None
        ndim = 2
   1386 if not allow_duplicate and len(set(axis)) != len(axis):
   1387     if argname:

File ~\AppData\Roaming\Python\Python38\site-packages\numpy\core\numeric.py:1385, in <listcomp>(.0=<tuple_iterator object>)
   1383         pass
   1384 # Going via an iterator directly is slower than via list comprehension.
-> 1385 axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
        argname = None
        ax = 2
        ndim = 2
   1386 if not allow_duplicate and len(set(axis)) != len(axis):
   1387     if argname:

AxisError: axis 2 is out of bounds for array of dimension 2

**Comment by kapoorlab** [comment]
Hello,

Thanks for pointing this out, I understand what this error means which is saying that the axis it gets for normalization is (0,1,2) whereas for a 2D image it should be (0,1), I will investigate why this is happening and try to reproduce it and will let you know as soon as I fix this from happening.

**Comment by kapoorlab** [comment]
Can you send me a screenshot of the vollseg napari plugin with the selection of parameters please, would make it easier to debug.

**Comment by Nal44** [comment]
Hi,

Yes,
find it attached.

I tried many times but could never make it run ...

thank you for the help,
antho

![vollseg](https://user-images.githubusercontent.com/64991735/168162746-35a73a78-367e-4255-95f6-8f47c231b456.png)

**Comment by kapoorlab** [comment]
Thanks, I clearly see that the reason it does not work is because the image is 2D and normalization axes is shown as ZYX, I will work on this and see if the latest version of mine still have this issue. Thanks for reporting, 
Cheers, Varun.

**Comment by Nal44** [comment]
Thanks,

I noticed that before , so I tried to change it manually to YX but it doesn't work.

thanks
antho

**Comment by kapoorlab** [comment]
Yes, I was able to reproduce this, I suspect this happened when I changed the code to accommodate RGB images for 2D segmentation, I will fix this tonight and release new VollSeg version which will fix it in the plugin.

**Comment by Nal44** [comment]
Great ! that was fast ! :)
Looking to try it !

Thank you so much,
Antho

**Comment by kapoorlab** [comment]
Hello, It is fixed in the vollseg version 4.4.0 I just released, please try and let me know if it works for you now, I will continue making more coverage tests to check other modes. Thanks for pointing this out.

**Comment by Nal44** [comment]
Is it the Napari version ?
I cannot see the update yet.

Thanks
antho

**Comment by kapoorlab** [comment]
No it is the VollSeg version, the napari version is the same. SO you just have to update the vollseg version, it was  bug coming from those functions.

**Comment by kapoorlab** [comment]
So you just have to pip install vollseg in the conda env of yours, let me know if you are able to get it working?

**Comment by Nal44** [comment]
I did directly into Napari  console.
It did the installation and I reboot but the problem is not fixed...
Is there another way to make the update ?

Thanks

**Comment by kapoorlab** [comment]
Maybe do the pip install from the anaconda prompt after closing the current Napari session and then relaunch napari again after the install, make sure that it is vollseg==4.4.0 that you have prior to launching Napari. Try that and let me know if that works.

To check the vollseg version, launch a python session from the terminal and then 

`import vollseg

print(vollseg.__version__)`
If you have 4.4.0 you should not have this problem anymore.

**Comment by Nal44** [comment]
I think for some reason I the version is still : 4.3.6
pip install --user vollseg
Requirement already satisfied: vollseg in appdata\roaming\python\python38\site-packages (4.3.6)

I cannot install the 4.4.0 using pip install .... ?

**Comment by kapoorlab** [comment]
you can try it like pip install vollseg==4.4.0 and then it will ignore the installed version.

With pip it also works if you do pip install vollseg --ignore-installed
or with pip install vollseg --upgrade

**Comment by Nal44** [comment]
It works now :)
Thanks for your help ,
antho

**Comment by Nal44** [comment]
Just playing around and new error : 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~\AppData\Roaming\Python\Python38\site-packages\vollseg_napari\_dock_widget.py:1829, in plugin_wrapper_vollseg.<locals>.return_segment(pred=((<class 'numpy.ndarray'> (1040, 1392) uint16, <class 'numpy.ndarray'> (1040, 1392) uint16, <class 'numpy.ndarray'> (1040, 1392) uint16, <class 'numpy.ndarray'> (1040, 1392) float64, <class 'numpy.ndarray'> (1040, 1392) uint16, <class 'numpy.ndarray'> (1040, 1392) uint16), [1.0, 1.0]))
   1826     labels, unet_mask, star_labels, probability_map, Markers, Skeleton, denoised_image, roi_image = res
   1828 elif plugin.den_model_type.value == DEFAULTS_MODEL['model_den_none'] and plugin.star_seg_model_type.value != DEFAULTS_MODEL['model_star_none'] and plugin.roi_model_type.value != DEFAULTS_MODEL['model_roi_none']:
-> 1829     labels, unet_mask, star_labels, probability_map, Markers, Skeleton, roi_image = res
        res = (<class 'numpy.ndarray'> (1040, 1392) uint16, <class 'numpy.ndarray'> (1040, 1392) uint16, <class 'numpy.ndarray'> (1040, 1392) uint16, <class 'numpy.ndarray'> (1040, 1392) float64, <class 'numpy.ndarray'> (1040, 1392) uint16, <class 'numpy.ndarray'> (1040, 1392) uint16)
   1831 elif plugin.star_seg_model_type.value == DEFAULTS_MODEL['model_star_none'] and plugin.roi_model_type.value != DEFAULTS_MODEL['model_roi_none']:
   1833     unet_mask, denoised_image, roi_image = res

ValueError: not enough values to unpack (expected 7, got 6)

**Comment by kapoorlab** [comment]
Aha, which setting did you try for this one? It seems you tried the roi model with the 2D stardist model. Actually for this case you should use Unet model instead of roi model, roi model is for 3D starDist + 2D/3D unet ROI mask.

**Comment by kapoorlab** [comment]
I should make this option illegal if that was the case, then you will not see the run button with this setting. Thanks for pointing this out too!

**Comment by Nal44** [comment]
Ok, yes this is exactly what I did ..  !
I am trying to learn all the options, to find the parameters that suit my image best.

Happy to help ! :)

antho

**Comment by kapoorlab** [comment]
Glad that you are helping, for 2D you can use StarDist + Unet, StarDist + CARE, StarDist + Unet + CARE with the option of getting the semantic segmentation from unet or Care by setting the vollseg parameter, BinaryMask from Unet on/off. Then you have size of mask and cells to play around with. Try some of the pre trained models also and then see if you can find a good setting for your use case :) and of course if you find more bugs am happy to fix them right away.

**Comment by Nal44** [comment]
ah, for some reason the CARE is always RED (denoise carcinoma), so I am not able to use it ...

**Comment by kapoorlab** [comment]
That is because it is a 3D model so it is good that it is red because 2D image can not be denoised with a 3D model, I did not train any 2D denoising model so for this one you would have to use some other CARE trained 2D model that you can load from the disk using the CustomCARE option.

**Comment by Nal44** [comment]
Ok make sense !

Great, I will train one, then and try, thank for your support !
antho

**Comment by kapoorlab** [comment]
Hey so I made more unit tests for different model combination, for my the stardist + roi model combination works in 2D in the plugin and also in my tests, what was your setting in 2D that made it fail with the roi model?

**Comment by Nal44** [comment]
Hi, that was with the denoised care , but you mentioned that is only works 3D and not 2D.

**Comment by kapoorlab** [comment]
Yes I am trying the change that function so it works for 2D also, in this case it will give you the same result as you will get using a Unet. Ok got it, denoise + maskunet was the fail case.

**Comment by kapoorlab** [comment]
Can you share your 2D denoising model, I could not find a pre-rained model for that.

**Comment by Nal44** [comment]
I dont have a pretrained model 2D for that, but I will later

**Comment by Nal44** [comment]
I am sorry but I don't have a CARE model yet 2D, but later I plan to train one,
So once I get a working model I will be able to share it,

**Comment by kapoorlab** [comment]
But how did you test the plugin with the 2D denoising model then? I do not need a very well working model just one that has the right class to test the code.

**Comment by Nal44** [comment]
I did not since I don't have a model,
I wanted to try it, so I assumed that a pretrained 2D model was available...
Sorry for the confusion,

**Comment by kapoorlab** [comment]
Hey Antho, I released new versions of both vollseg and vollseg-napari after testing different model combinations. So you can do

pip install vollseg-napari --ignore-installed and 
pip install vollseg --ignore-installed

to get the latest versions and they give the plugin a try witht hte pre trained models and samp^le images that ship with Napari and the vollseg-napari plugin and if you see the run button being available you should be able to get the results without error. If so then feel free to close the issue and thank you so much for testing.

Cheers,
Varun

**Comment by Nal44** [comment]
Hi Varun,

It works as expected, thanks a lot, I will keep in touch if I encounter any further bugs,
Thanks for the support !
antho
